bestblock,getmemoryinfo,uptime collectors added

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,32 +27,38 @@ jobs:
         run: |
           poetry run flake8 .
           poetry run mypy --warn-unused-ignores .
-
-  test:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        bitcoind_version: ["0.19", "0.20", "0.21", "22", "23"]
-    name: Test with bitcoin-core:${{ matrix.bitcoind_version }}
-    steps:
-    - uses: actions/checkout@v3
-    - name: Set up Python 3.8
-      uses: actions/setup-python@v3
-      with:
-        python-version: "3.8"
-    - name: Run bitcoind ${{ matrix.bitcoind_version }}
-      run: |
-        docker create --name=bitcoind --health-cmd="curl -s --fail --data-binary '{\"jsonrpc\":\"1.0\",\"id\":\"curltext\",\"method\":\"getblockchaininfo\",\"params\":[]}' -H 'content-type:text/plain;' http://bitcoind:bitcoind@localhost:8332/ || exit 1" -p8332:8332 -v $(pwd)/staff/bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf ruimarinho/bitcoin-core:${{ matrix.bitcoind_version }}
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install poetry
-        poetry install --no-root
-    - name: Test
-      env:
-        BITCOIND: http://bitcoind:bitcoind@127.0.0.1:8332
-      run: |
-        poetry run pytest -vx --log-level=0 --cov=bitcoind_exporter --asyncio-mode=strict tests/
+  # Not mounting config files is supported ;(
+  # test:
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       bitcoind_version: ["0.19", "0.20", "0.21", "22", "23"]
+  #   name: Test with bitcoin-core:${{ matrix.bitcoind_version }}
+  #   services:
+  #     bitcoind:
+  #       image: ruimarinho/bitcoin-core:${{ matrix.bitcoind_version }}
+  #       options: >-
+  #         -v "${{ github.workspace }}/staff/bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf"
+  #         --health-cmd="curl -s --fail --data-binary '{\"jsonrpc\":\"1.0\",\"id\":\"curltext\",\"method\":\"getblockchaininfo\",\"params\":[]}' -H 'content-type:text/plain;' http://bitcoind:bitcoind@localhost:8332/ || exit 1"
+  #         --health-interval 10s
+  #         --health-timeout 5s
+  #         --health-retries 5
+  #   steps:
+  #   - uses: actions/checkout@v3
+  #   - name: Set up Python 3.8
+  #     uses: actions/setup-python@v3
+  #     with:
+  #       python-version: "3.8"
+  #   - name: Install dependencies
+  #     run: |
+  #       python -m pip install --upgrade pip
+  #       pip install poetry
+  #       poetry install --no-root
+  #   - name: Test
+  #     env:
+  #       BITCOIND: http://bitcoind:bitcoind@bitcoind:8332
+  #     run: |
+  #       poetry run pytest -vx --log-level=0 --cov=bitcoind_exporter --asyncio-mode=strict tests/
 
   build-and-push-image:
     runs-on: ubuntu-latest
